repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (lint)
        entry: uv run -- ruff
        language: system
        types: [python]
        args: [check, --fix]

      - id: ruff-format
        name: ruff (format)
        entry: uv run -- ruff
        language: system
        types: [python]
        args: [format]